import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Merky Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-merky-dark sınıfını buraya ekliyoruz */}
      <body className={`${inter.className} bg-merky-dark text-white`}>
      
        {children}
      </body>
    </html>
  );
}